# Generated by Django 6.0.4 on 2026-05-04 12:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_code', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('guest', 'Guest'), ('suspended', 'Suspended')], default='active', max_length=24)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supabase_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('checked_in', 'Checked in'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='reserved', max_length=24)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('front_desk', 'Front desk')], default='web', max_length=24)),
                ('attendee_count', models.PositiveIntegerField(default=1)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('external_payment_reference', models.CharField(blank=True, max_length=160)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='reservations.customer')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(max_length=80)),
                ('path', models.CharField(max_length=512)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('waiver', 'Waiver'), ('avatar', 'Avatar'), ('evidence', 'Evidence')], max_length=24)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.booking')),
                ('owner_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.customer')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_kind', models.CharField(choices=[('membership', 'Membership'), ('credit_pack', 'Credit pack'), ('day_pass', 'Day pass')], max_length=24)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('remaining_credits', models.PositiveIntegerField(default=0)),
                ('external_payment_reference', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='reservations.customer')),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=120)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_entries', to='reservations.booking')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='reservations.membership')),
            ],
            options={
                'db_table': 'credit_ledger',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=64)),
                ('address', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='reservations.organization')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='reservations.organization'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='reservations.profile'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('resource_kind', models.CharField(choices=[('pool_lane', 'Pool lane'), ('room', 'Room'), ('entry_gate', 'Entry gate')], max_length=24)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='reservations.location')),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('service_kind', models.CharField(choices=[('pool', 'Pool'), ('personal_training', 'Personal training'), ('massage', 'Massage'), ('day_pass', 'Day pass')], max_length=32)),
                ('duration_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('slot_interval_min', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_mode', models.CharField(choices=[('shared_capacity', 'Shared capacity'), ('staff_exclusive', 'Staff exclusive'), ('staff_and_resource', 'Staff and resource'), ('entitlement', 'Entitlement')], max_length=32)),
                ('requires_staff', models.BooleanField(default=False)),
                ('requires_resource', models.BooleanField(default=False)),
                ('price_amount', models.PositiveIntegerField(default=0)),
                ('price_currency', models.CharField(default='TRY', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='reservations.location')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='reservations.service'),
        ),
        migrations.CreateModel(
            name='SlotInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity_total', models.PositiveIntegerField(default=1)),
                ('capacity_reserved', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='reservations.resource')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='reservations.service')),
            ],
            options={
                'db_table': 'slot_inventory',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='reservations.slotinventory'),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('role_kind', models.CharField(choices=[('admin', 'Admin'), ('front_desk', 'Front desk'), ('trainer', 'Trainer'), ('therapist', 'Therapist')], max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='reservations.organization')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_roles', to='reservations.profile')),
            ],
            options={
                'db_table': 'staff_members',
            },
        ),
        migrations.AddField(
            model_name='slotinventory',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='reservations.staffmember'),
        ),
        migrations.CreateModel(
            name='ServiceStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_staff', to='reservations.service')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_services', to='reservations.staffmember')),
            ],
            options={
                'db_table': 'service_staff',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('qr', 'QR'), ('membership_code', 'Membership code'), ('manual', 'Manual')], max_length=32)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='check_in', to='reservations.booking')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.staffmember')),
            ],
            options={
                'db_table': 'check_ins',
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('service', 'Service'), ('staff', 'Staff'), ('resource', 'Resource')], max_length=16)),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_blackout', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='reservations.location')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.resource')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.service')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.staffmember')),
            ],
            options={
                'db_table': 'availability_rules',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expo_push_token', models.CharField(max_length=220)),
                ('platform', models.CharField(blank=True, max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='reservations.customer')),
            ],
            options={
                'db_table': 'device_tokens',
                'constraints': [models.UniqueConstraint(fields=('customer', 'expo_push_token'), name='unique_customer_device')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'membership_code'), name='unique_membership_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='slotinventory',
            index=models.Index(fields=['service', 'starts_at'], name='slot_invent_service_bf51e9_idx'),
        ),
        migrations.AddIndex(
            model_name='slotinventory',
            index=models.Index(fields=['staff_member', 'starts_at'], name='slot_invent_staff_m_f997b8_idx'),
        ),
        migrations.AddIndex(
            model_name='slotinventory',
            index=models.Index(fields=['resource', 'starts_at'], name='slot_invent_resourc_6c129c_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicestaff',
            constraint=models.UniqueConstraint(fields=('service', 'staff_member'), name='unique_service_staff'),
        ),
    ]
