# Generated by Django 6.0.4 on 2026-05-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('terminated', 'Terminated')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='role_kind',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('personal_trainer', 'Personal trainer'), ('front_desk', 'Front desk'), ('therapist', 'Therapist')], max_length=24),
        ),
    ]
