# Generated by Django 6.0.4 on 2026-05-05 01:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_customer_deactivated_at_customer_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('session_kind', models.CharField(choices=[('personal_training', 'Personal training'), ('yoga', 'Yoga'), ('swimming_lesson', 'Swimming lesson'), ('boxing', 'Boxing'), ('pilates', 'Pilates'), ('rehab', 'Rehab'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=24)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('external_pending', 'External pending')], default='external_pending', max_length=24)),
                ('payment_amount', models.PositiveIntegerField(default=0)),
                ('payment_currency', models.CharField(default='TRY', max_length=3)),
                ('external_payment_reference', models.CharField(blank=True, max_length=160)),
                ('total_sessions', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('default_duration_min', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_session_plans', to='reservations.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_session_plans', to='reservations.organization')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_session_plans', to='reservations.staffmember')),
            ],
            options={
                'db_table': 'training_session_plans',
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=24)),
                ('location_name', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='reservations.trainingsessionplan')),
            ],
            options={
                'db_table': 'training_session_occurrences',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsessionplan',
            index=models.Index(fields=['organization', 'status'], name='training_se_organiz_39630e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionplan',
            index=models.Index(fields=['trainer', 'status'], name='training_se_trainer_a09cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionplan',
            index=models.Index(fields=['customer', 'status'], name='training_se_custome_578b77_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionplan',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='training_session_plan_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionoccurrence',
            index=models.Index(fields=['starts_at', 'ends_at'], name='training_se_starts__1c6337_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionoccurrence',
            index=models.Index(fields=['status', 'starts_at'], name='training_se_status_ee757a_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionoccurrence',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence_number'), name='unique_training_session_sequence'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='training_session_ends_after_start'),
        ),
    ]
