# Generated by Django 6.0.4 on 2026-05-05 02:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_trainingsessionplan_trainingsessionoccurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=120)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.CharField(max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainingsessionplan',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsessionplan',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsessionplan',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingsessionplan',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='trainingsessionoccurrence',
            index=models.Index(fields=['plan', 'starts_at'], name='training_se_plan_id_df50da_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.profile'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.staffmember'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='reservations.organization'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'created_at'], name='audit_logs_organiz_af0d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx'),
        ),
    ]
