# Generated by Django 6.0.4 on 2026-05-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auditlog_trainingsessionplan_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trainingsessionplan',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('payment_amount'))), name='training_session_amount_paid_lte_amount'),
        ),
    ]
