# Generated by Django 6.0.4 on 2026-05-08 01:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_trainingprogram_trainingprogramassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('qr', 'QR'), ('membership_code', 'Membership code'), ('manual', 'Manual'), ('kiosk', 'Kiosk')], default='membership_code', max_length=32)),
                ('source', models.CharField(choices=[('front_desk', 'Front desk'), ('member_app', 'Member app'), ('kiosk', 'Kiosk'), ('import', 'Import')], default='front_desk', max_length=32)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'member_check_ins',
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('product_kind', models.CharField(choices=[('membership', 'Membership'), ('credit_pack', 'Credit pack'), ('day_pass', 'Day pass')], max_length=24)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('session_pack', 'Session pack'), ('one_time', 'One time')], default='monthly', max_length=24)),
                ('access_rule', models.CharField(choices=[('unlimited', 'Unlimited'), ('limited_visits', 'Limited visits'), ('classes_only', 'Classes only'), ('appointments_only', 'Appointments only')], default='unlimited', max_length=32)),
                ('visit_limit_per_period', models.PositiveIntegerField(blank=True, null=True)),
                ('session_credit_amount', models.PositiveIntegerField(default=0)),
                ('price_amount', models.PositiveIntegerField(default=0)),
                ('price_currency', models.CharField(default='TRY', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'membership_plans',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='trainingprogram',
            new_name='training_pr_organiz_649c48_idx',
            old_name='training_pr_organiz_d6bc41_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingprogram',
            new_name='training_pr_organiz_a5e17f_idx',
            old_name='training_pr_organiz_a8c1a6_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingprogramassignment',
            new_name='training_pr_organiz_8b9bf6_idx',
            old_name='training_pr_organiz_a2b705_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingprogramassignment',
            new_name='training_pr_custome_39d785_idx',
            old_name='training_pr_customer_8f9fa1_idx',
        ),
        migrations.RenameIndex(
            model_name='trainingprogramassignment',
            new_name='training_pr_assigne_dc69be_idx',
            old_name='training_pr_assigne_318915_idx',
        ),
        migrations.AddField(
            model_name='membership',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='membercheckin',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_check_ins', to='reservations.customer'),
        ),
        migrations.AddField(
            model_name='membercheckin',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.staffmember'),
        ),
        migrations.AddField(
            model_name='membercheckin',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins', to='reservations.membership'),
        ),
        migrations.AddField(
            model_name='membercheckin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_check_ins', to='reservations.organization'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='reservations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='reservations.membershipplan'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['customer', 'status'], name='memberships_custome_5d0178_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['valid_to', 'status'], name='memberships_valid_t_be86ba_idx'),
        ),
        migrations.AddIndex(
            model_name='membercheckin',
            index=models.Index(fields=['organization', 'checked_in_at'], name='member_chec_organiz_e7ff74_idx'),
        ),
        migrations.AddIndex(
            model_name='membercheckin',
            index=models.Index(fields=['customer', 'checked_in_at'], name='member_chec_custome_91ecec_idx'),
        ),
        migrations.AddIndex(
            model_name='membercheckin',
            index=models.Index(fields=['handled_by', 'checked_in_at'], name='member_chec_handled_2562fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_membership_plan_name_per_org'),
        ),
    ]
